travis:
  secure:
    BINSTAR_TOKEN: kI+JsrLLCt2WbZSPe9VADB95mEpm0DjDIQR7e0e/5Z+QIRbHNb/oNHJwlDv6JLu0+nl5A54DBYcIIWzKcOJFZZR7YSjGXZ3PXWiO4VLDgUYJJ0VpH7Ym+H4p7qLF/0v4RjByECY2TAP7NB4gmS5tSUOK2u/EdO80PL2vfYqqQvtKTBgm60eX+CiKRguj0AbwlYULa/lx8R2rr5VWdUed2EGfpoqMupp1D6IQuku9yYdTeaAHJLGNt+5UIzT50ja+MMfMULv1sXRvVrQlmpVTBCJSCThBKMzg7ysmMUn0Qb/dMMWZkxH+IUIIwmigVcpDxXMgO2Zprn/pqXlbabo2W93WkDNtOQ5fb2soqiwkbSmbt0dsGnm72pSGv+X3yr7OWi++TnhpVA3HzQZfYNcpBzQWKjao/y5whTS6b7h2Lk6jjtF/urRfk+1QEx97zJiGi6LvPc15JE3E1QCV/SsK16JwNmVAm+RUr3rAY0EyGhtqAyxcbSycUH73CJal9xCCoARKIZc51gztZXSa2L96BahlmFZu8gPr8QQgTlQwsorDrtuAzzld53M7MMzXI7GGZQmue+PO5mCFT1bgN9RDEtCBSv4+/pBwwH0wQakQVhxUKsCik0bKZeCVQH2X74l2sqw3zyrzy63R2Stke6XjYoUcLX+EmS+I8/Ek+5Cpdys=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
